# Operations
batch_acc_to_db:
  pointer:  operations.accounting.store_acc_summary_and_portfolio_from_ib_to_db
print_acc_port:
  pointer:  operations.accounting.print_10_days_acc_summary_and_current_positions
batch_orders_to_db:
  pointer:  operations.orders.store_orders_from_ib_to_db
migrate_h5_orders_sqlite:
  pointer:  operations.orders.migrate_h5_to_sqllite_orders
migrate_h5_port_sqlite:
  pointer:  operations.accounting.migrate_h5_to_sqllite_portfolio
migrate_h5_acc_sqlite:
  pointer:  operations.accounting.migrate_h5_to_sqllite_acc_summary

# Market data
migrate_h5_optchain_ib_sqlite:
  pointer:  operations.market_data.migrate_h5_to_sqllite_optchain_ib
migrate_h5_optchain_yhoo_sqlite:
  pointer:  operations.market_data.migrate_h5_to_sqllite_optchain_yahoo
batch_optchain_yhoo_to_db:
  pointer:  operations.market_data.store_optchain_yahoo_to_db

# Web reporting generation
run_dq_report_market:
  pointer: analytics.dq_report.run_dq_report_market

# trend and risk indicators
coppock:
   pointer: analytics.analytics_methods.print_coppock_diario
emas:
   pointer: analytics.analytics_methods.print_emas
summary:
  pointer: analytics.analytics_methods.print_summary_underl
vol:
  pointer: analytics.analytics_methods.print_volatity
fastmove:
  pointer: analytics.analytics_methods.print_fast_move
cone:
  pointer: analytics.analytics_methods.print_volatility_cone

# pretrade analysis commands
lstprc:
   pointer: volibutils.orders_methods.list_prices_before_trade
lstchain:
  pointer: analytics.analytics_methods.print_quasi_realtime_chain
lstspreadprc:
   pointer: volibutils.orders_methods.list_spread_prices_before_trade
chainprc:
   pointer: volibutils.orders_methods.list_option_chain
hist_opt:
   pointer: analytics.analytics_methods.print_historical_option
ecocal:
   pointer: analytics.analytics_methods.print_ecalendar
simul_tic:
   pointer: analytics.analytics_methods.print_TBD

# Order commands
fill1opt:
   pointer: volibutils.orders_methods.place_plain_order
   typecast:
      strike: float
      quantity: int
      lmtPrice: float
      orderId: int
fill1spread:
   pointer: volibutils.orders_methods.place_or_modif_spread_order
   typecast:
      strike_l: float
      strike_s: float
      quantity: int
      lmtPrice: float
      orderId: int
lstorders:
   pointer: volibutils.orders_methods.list_open_orders
cancel:
   pointer: volibutils.orders_methods.cancel_open_order
   typecast:
      orderId: int
cancelall:
   pointer: volibutils.orders_methods.cancel_all_open_orders

# TIC portfolio management
ticrpt:
   pointer: analytics.analytics_methods.print_tic_report
#portfolio:
#   pointer: operations.vol_grab_accounting.print_portfolio_from_ib
accdelta:
  pointer: analytics.analytics_methods.print_account_delta
accsnap:
  pointer: analytics.analytics_methods.print_account_snapshot

# general market analysis
hist_under:
   pointer: analytics.analytics_methods.print_historical_underl

# Batch commands & anciliary commands
batch_tic_rpt:
   pointer: analytics.shark_tic_report.run_report
fix_ecalendar:
  pointer: volsetup.fix_h5_economic_calendar.run
fix_histo_optchain:
  pointer: volsetup.fix_h5_historical_opt.run

batch_hist_underlying:
  pointer:  volquotes.historical_data_loader.run_reader
batch_hist_options:
  pointer:  volquotes.historical_opt_chains_loader.run_reader



# DONT USE
fix_acc_h5:
  pointer:  operations.accounting.consolidate_anciliary_h5_account
fix_port_h5:
  pointer:  operations.accounting.consolidate_anciliary_h5_portfolio
fix_orders_h5:
  pointer:  operations.orders.consolidate_anciliary_h5_orders
fix_optchain:
  pointer: volsetup.fix_h5_optchain_ib.run
fix_optchain_yhoo:
  pointer: volsetup.fix_h5_yahoo_optchain.run


