# Used in crontab for automated data gathering
batch_acc_to_db:
  pointer:  operations.accounting.store_acc_summary_and_portfolio_from_ib_to_db
batch_orders_to_db:
  pointer:  operations.orders.store_orders_from_ib_to_db
batch_optchain_yhoo_to_db:
  pointer:  core.market_data_methods.store_optchain_yahoo_to_db
batch_underl_ib_to_db:
  pointer:  core.market_data_methods.store_underlying_ib_to_db
batch_itrm_wraps:
  pointer:  webscrape.market_wrap_reader.run_reader

# One shot jobs for initial loading
init_itrm_wraps:
  pointer:  webscrape.market_wrap_reader.first_run


# Web reporting generation
run_dq_report_market:
  pointer: core.reporting.run_dq_report_market
run_volest_report:
  pointer: core.reporting.run_volest_report
run_trend_report:
  pointer: core.reporting.run_trend_report
# H5 legacy
migrate_h5:
  pointer:  core.h5_legacy_methods.migrate_h5
# Operations
print_acc_port:
  pointer:  operations.accounting.print_10_days_acc_summary_and_current_positions
# trend and risk indicators
coppock:
   pointer: core.analytics_methods.print_coppock_diario
emas:
   pointer: core.analytics_methods.print_emas
vol:
  pointer: core.analytics_methods.print_volatity
fastmove:
  pointer: core.analytics_methods.print_fast_move
summary:
  pointer: core.analytics_methods.print_summary_underl

# pretrade analysis commands
lstprc:
   pointer: volibutils.orders_methods.list_prices_before_trade
lstchain:
  pointer: core.analytics_methods.print_chain
lstspreadprc:
   pointer: volibutils.orders_methods.list_spread_prices_before_trade
chainprc:
   pointer: volibutils.orders_methods.list_option_chain
hist_opt:
   pointer: core.analytics_methods.print_historical_option


accdelta:
  pointer: core.analytics_methods.print_account_delta
accsnap:
  pointer: core.analytics_methods.print_account_snapshot


##### NEED TO REVIEW

ecocal:
   pointer: core.analytics_methods.print_ecalendar

# Order commands
fill1opt:
   pointer: volibutils.orders_methods.place_plain_order
   typecast:
      strike: float
      quantity: int
      lmtPrice: float
      orderId: int
fill1spread:
   pointer: volibutils.orders_methods.place_or_modif_spread_order
   typecast:
      strike_l: float
      strike_s: float
      quantity: int
      lmtPrice: float
      orderId: int
lstorders:
   pointer: volibutils.orders_methods.list_open_orders
cancel:
   pointer: volibutils.orders_methods.cancel_open_order
   typecast:
      orderId: int
cancelall:
   pointer: volibutils.orders_methods.cancel_all_open_orders
# TIC portfolio management
ticrpt:
   pointer: core.analytics_methods.print_tic_report
#portfolio:
#   pointer: operations.vol_grab_accounting.print_portfolio_from_ib
# general market analysis
hist_under:
   pointer: core.analytics_methods.print_historical_underl
# Batch commands & anciliary commands
batch_tic_rpt:
   pointer: core.shark_tic_report.run_report
batch_hist_options:
  pointer:  volquotes.historical_opt_chains_loader.run_reader
