fill1opt:
   pointer: volibutils.orders_methods.place_plain_order
   typecast:
      strike: float
      quantity: int
      lmtPrice: float
      orderId: int
fill1spread:
   pointer: volibutils.orders_methods.place_or_modif_spread_order
   typecast:
      strike_l: float
      strike_s: float
      quantity: int
      lmtPrice: float
      orderId: int
lstorders:
   pointer: volibutils.orders_methods.list_open_orders
cancel:
   pointer: volibutils.orders_methods.cancel_open_order
   typecast:
      orderId: int
cancelall:
   pointer: volibutils.orders_methods.cancel_all_open_orders
lstprc:
   pointer: volibutils.orders_methods.list_prices_before_trade
lstspreadprc:
   pointer: volibutils.orders_methods.list_spread_prices_before_trade
manualfill:
   pointer: manualfill.manualfill
   typecast:
      fill_price: float
      orderid: int
      fill: int

