# trend and risk indicators
coppock:
   pointer: voldailyanalytics.analytics_methods.print_coppock_diario
emas:
   pointer: voldailyanalytics.analytics_methods.print_emas
summary:
  pointer: voldailyanalytics.analytics_methods.print_summary_underl
vol:
  pointer: voldailyanalytics.analytics_methods.print_volatity
fastmove:
  pointer: voldailyanalytics.analytics_methods.print_fast_move
cone:
  pointer: voldailyanalytics.analytics_methods.print_volatility_cone

# pretrade analysis commands
lstprc:
   pointer: volibutils.orders_methods.list_prices_before_trade
lstchain:
  pointer: voldailyanalytics.analytics_methods.print_quasi_realtime_chain
lstspreadprc:
   pointer: volibutils.orders_methods.list_spread_prices_before_trade
chainprc:
   pointer: volibutils.orders_methods.list_option_chain
hist_opt:
   pointer: voldailyanalytics.analytics_methods.print_historical_option
ecocal:
   pointer: voldailyanalytics.analytics_methods.print_ecalendar
simul_tic:
   pointer: voldailyanalytics.analytics_methods.print_TBD

# Order commands
fill1opt:
   pointer: volibutils.orders_methods.place_plain_order
   typecast:
      strike: float
      quantity: int
      lmtPrice: float
      orderId: int
fill1spread:
   pointer: volibutils.orders_methods.place_or_modif_spread_order
   typecast:
      strike_l: float
      strike_s: float
      quantity: int
      lmtPrice: float
      orderId: int
lstorders:
   pointer: volibutils.orders_methods.list_open_orders
cancel:
   pointer: volibutils.orders_methods.cancel_open_order
   typecast:
      orderId: int
cancelall:
   pointer: volibutils.orders_methods.cancel_all_open_orders

# TIC portfolio management
ticrpt:
   pointer: voldailyanalytics.analytics_methods.print_tic_report
portfolio:
   pointer: volaccounting.vol_grab_accounting.print_portfolio_data
accdelta:
  pointer: voldailyanalytics.analytics_methods.print_account_delta
accsnap:
  pointer: voldailyanalytics.analytics_methods.print_account_snapshot

# general market analysis
hist_under:
   pointer: voldailyanalytics.analytics_methods.print_historical_underl

# Batch commands & anciliary commands
batch_tic_rpt:
   pointer: voldailyanalytics.shark_tic_report.run_report
fix_ecalendar:
  pointer: volsetup.fix_h5_economic_calendar.run
fix_optchain:
  pointer: volsetup.fix_h5_optchain_ib.run
fix_optchain_yhoo:
  pointer: volsetup.fix_h5_yahoo_optchain.run
batch_account:
  pointer:  volaccounting.vol_grab_accounting.run_get_portfolio_data
batch_hist_underlying:
  pointer:  volquotes.historical_data_loader.run_reader
batch_hist_options:
  pointer:  volquotes.historical_opt_chains_loader.run_reader

