fill1opt:
   pointer: volibutils.orders_methods.place_plain_order
   typecast:
      strike: float
      quantity: int
      lmtPrice: float
      orderId: int
fill1spread:
   pointer: volibutils.orders_methods.place_or_modif_spread_order
   typecast:
      strike_l: float
      strike_s: float
      quantity: int
      lmtPrice: float
      orderId: int
lstorders:
   pointer: volibutils.orders_methods.list_open_orders
cancel:
   pointer: volibutils.orders_methods.cancel_open_order
   typecast:
      orderId: int
cancelall:
   pointer: volibutils.orders_methods.cancel_all_open_orders
lstprc:
   pointer: volibutils.orders_methods.list_prices_before_trade
lstspreadprc:
   pointer: volibutils.orders_methods.list_spread_prices_before_trade
ticrpt:
   pointer: voldailyanalytics.analytics_methods.print_tic_report
chainprc:
   pointer: volibutils.orders_methods.list_option_chain
portfolio:
   pointer: volaccounting.vol_grab_accounting.print_portfolio_data
hist_under:
   pointer: voldailyanalytics.analytics_methods.print_historical_underl
hist_chain:
   pointer: voldailyanalytics.analytics_methods.print_historical_chain
coppock:
   pointer: voldailyanalytics.analytics_methods.print_coppock_diario
emas:
   pointer: voldailyanalytics.analytics_methods.print_emas
batch_tic_rpt:
   pointer: voldailyanalytics.shark_tic_report.run_report
summary:
  pointer: voldailyanalytics.analytics_methods.print_summary_underl
vol:
  pointer: voldailyanalytics.analytics_methods.print_volatity
fastmove:
  pointer: voldailyanalytics.analytics_methods.print_fast_move
