CREATE TABLE IF NOT EXISTS "OPTIONS_CHAIN_IB" (
"load_dttm" TIMESTAMP   not null ,
  "symbol" char(5)    not null ,
  "secType" char(4) ,
  "expiry" TIMESTAMP    not null,
  "strike" REAL    not null ,
  "right" char(1)    not null,
  "multiplier" REAL,
  "exchange" char(8),
  "currency" char(3),
  "comboLegsDescrip" char(5),
  "bidPrice" REAL,
  "bidSize" REAL,
  "askPrice" REAL,
  "askSize" REAL,
  "lastPrice" REAL,
  "lastSize" REAL,
  "closePrice" REAL,
  "modelImpliedVol" REAL,
  "modelDelta" REAL,
  "modelOptPrice" REAL,
  "modelPvDividend" REAL,
  "modelGamma" REAL,
  "modelVega" REAL,
  "modelTheta" REAL,
  "modelUndPrice" REAL,
  "bidImpliedVol" REAL,
  "bidDelta" REAL,
  "bidOptPrice" REAL,
  "bidPvDividend" REAL,
  "bidGamma" REAL,
  "bidVega" REAL,
  "bidTheta" REAL,
  "bidUndPrice" REAL,
  "askImpliedVol" REAL,
  "askDelta" REAL,
  "askOptPrice" REAL,
  "askPvDividend" REAL,
  "askGamma" REAL,
  "askVega" REAL,
  "askTheta" REAL,
  "askUndPrice" REAL,
  "lastImpliedVol" REAL,
  "lastDelta" REAL,
  "lastOptPrice" REAL,
  "lastPvDividend" REAL,
  "lastGamma" REAL,
  "lastVega" REAL,
  "lastTheta" REAL,
  "lastUndPrice" REAL,
  "CallOI" REAL,
  "PutOI" REAL,
  "Volume" REAL,
  "highPrice" REAL,
  "lowPrice" REAL,
   PRIMARY KEY("load_dttm","symbol", "expiry","strike", "right" )
);
CREATE INDEX "ix_OPTIONS_CHAIN_IB_index"ON "OPTIONS_CHAIN_IB" ("load_dttm");
