CREATE TABLE IF NOT EXISTS "USO" (
"Quote_Time" TIMESTAMP,
  "Strike" REAL,
  "Type" TEXT,
  "Symbol" TEXT,
  "Last" REAL,
  "Bid" REAL,
  "Ask" REAL,
  "Chg" REAL,
  "PctChg" REAL,
  "Vol" REAL,
  "Open_Int" REAL,
  "IV" REAL,
  "Root" TEXT,
  "IsNonstandard" INTEGER,
  "Underlying" TEXT,
  "Underlying_Price" REAL,
  "Last_Trade_Date" TIMESTAMP,
  "JSON" TEXT,
  "Quote_Time_txt" TEXT,
  "Last_Trade_Date_txt" TEXT,
  "Expiry_txt" TEXT
);
CREATE INDEX "ix_USO_Quote_Time"ON "USO" ("Quote_Time");
CREATE TABLE IF NOT EXISTS "IWM" (
"Quote_Time" TIMESTAMP,
  "Strike" REAL,
  "Type" TEXT,
  "Symbol" TEXT,
  "Last" REAL,
  "Bid" REAL,
  "Ask" REAL,
  "Chg" REAL,
  "PctChg" REAL,
  "Vol" REAL,
  "Open_Int" REAL,
  "IV" REAL,
  "Root" TEXT,
  "IsNonstandard" INTEGER,
  "Underlying" TEXT,
  "Underlying_Price" REAL,
  "Last_Trade_Date" TIMESTAMP,
  "JSON" TEXT,
  "Quote_Time_txt" TEXT,
  "Last_Trade_Date_txt" TEXT,
  "Expiry_txt" TEXT
);
CREATE INDEX "ix_IWM_Quote_Time"ON "IWM" ("Quote_Time");
CREATE TABLE IF NOT EXISTS "FXE" (
"Quote_Time" TIMESTAMP,
  "Strike" REAL,
  "Type" TEXT,
  "Symbol" TEXT,
  "Last" REAL,
  "Bid" REAL,
  "Ask" REAL,
  "Chg" REAL,
  "PctChg" REAL,
  "Vol" REAL,
  "Open_Int" REAL,
  "IV" REAL,
  "Root" TEXT,
  "IsNonstandard" INTEGER,
  "Underlying" TEXT,
  "Underlying_Price" REAL,
  "Last_Trade_Date" TIMESTAMP,
  "JSON" TEXT,
  "Quote_Time_txt" TEXT,
  "Last_Trade_Date_txt" TEXT,
  "Expiry_txt" TEXT
);
CREATE INDEX "ix_FXE_Quote_Time"ON "FXE" ("Quote_Time");
CREATE TABLE IF NOT EXISTS "GLD" (
"Quote_Time" TIMESTAMP,
  "Strike" REAL,
  "Type" TEXT,
  "Symbol" TEXT,
  "Last" REAL,
  "Bid" REAL,
  "Ask" REAL,
  "Chg" REAL,
  "PctChg" REAL,
  "Vol" REAL,
  "Open_Int" REAL,
  "IV" REAL,
  "Root" TEXT,
  "IsNonstandard" INTEGER,
  "Underlying" TEXT,
  "Underlying_Price" REAL,
  "Last_Trade_Date" TIMESTAMP,
  "JSON" TEXT,
  "Quote_Time_txt" TEXT,
  "Last_Trade_Date_txt" TEXT,
  "Expiry_txt" TEXT
);
CREATE INDEX "ix_GLD_Quote_Time"ON "GLD" ("Quote_Time");
CREATE TABLE IF NOT EXISTS "FXY" (
"Quote_Time" TIMESTAMP,
  "Strike" REAL,
  "Type" TEXT,
  "Symbol" TEXT,
  "Last" REAL,
  "Bid" REAL,
  "Ask" REAL,
  "Chg" REAL,
  "PctChg" REAL,
  "Vol" REAL,
  "Open_Int" REAL,
  "IV" REAL,
  "Root" TEXT,
  "IsNonstandard" INTEGER,
  "Underlying" TEXT,
  "Underlying_Price" REAL,
  "Last_Trade_Date" TIMESTAMP,
  "JSON" TEXT,
  "Quote_Time_txt" TEXT,
  "Last_Trade_Date_txt" TEXT,
  "Expiry_txt" TEXT
);
CREATE INDEX "ix_FXY_Quote_Time"ON "FXY" ("Quote_Time");
CREATE TABLE IF NOT EXISTS "VXX" (
"Quote_Time" TIMESTAMP,
  "Strike" REAL,
  "Type" TEXT,
  "Symbol" TEXT,
  "Last" REAL,
  "Bid" REAL,
  "Ask" REAL,
  "Chg" REAL,
  "PctChg" REAL,
  "Vol" REAL,
  "Open_Int" REAL,
  "IV" REAL,
  "Root" TEXT,
  "IsNonstandard" INTEGER,
  "Underlying" TEXT,
  "Underlying_Price" REAL,
  "Last_Trade_Date" TIMESTAMP,
  "JSON" TEXT,
  "Quote_Time_txt" TEXT,
  "Last_Trade_Date_txt" TEXT,
  "Expiry_txt" TEXT
);
CREATE INDEX "ix_VXX_Quote_Time"ON "VXX" ("Quote_Time");
CREATE TABLE IF NOT EXISTS "EMB" (
"Quote_Time" TIMESTAMP,
  "Strike" REAL,
  "Type" TEXT,
  "Symbol" TEXT,
  "Last" REAL,
  "Bid" REAL,
  "Ask" REAL,
  "Chg" REAL,
  "PctChg" REAL,
  "Vol" REAL,
  "Open_Int" REAL,
  "IV" REAL,
  "Root" TEXT,
  "IsNonstandard" INTEGER,
  "Underlying" TEXT,
  "Underlying_Price" REAL,
  "Last_Trade_Date" TIMESTAMP,
  "JSON" TEXT,
  "Quote_Time_txt" TEXT,
  "Last_Trade_Date_txt" TEXT,
  "Expiry_txt" TEXT
);
CREATE INDEX "ix_EMB_Quote_Time"ON "EMB" ("Quote_Time");
CREATE TABLE IF NOT EXISTS "VNQ" (
"Quote_Time" TIMESTAMP,
  "Strike" REAL,
  "Type" TEXT,
  "Symbol" TEXT,
  "Last" REAL,
  "Bid" REAL,
  "Ask" REAL,
  "Chg" REAL,
  "PctChg" REAL,
  "Vol" REAL,
  "Open_Int" REAL,
  "IV" REAL,
  "Root" TEXT,
  "IsNonstandard" INTEGER,
  "Underlying" TEXT,
  "Underlying_Price" REAL,
  "Last_Trade_Date" TIMESTAMP,
  "JSON" TEXT,
  "Quote_Time_txt" TEXT,
  "Last_Trade_Date_txt" TEXT,
  "Expiry_txt" TEXT
);
CREATE INDEX "ix_VNQ_Quote_Time"ON "VNQ" ("Quote_Time");
CREATE TABLE IF NOT EXISTS "TLT" (
"Quote_Time" TIMESTAMP,
  "Strike" REAL,
  "Type" TEXT,
  "Symbol" TEXT,
  "Last" REAL,
  "Bid" REAL,
  "Ask" REAL,
  "Chg" REAL,
  "PctChg" REAL,
  "Vol" REAL,
  "Open_Int" REAL,
  "IV" REAL,
  "Root" TEXT,
  "IsNonstandard" INTEGER,
  "Underlying" TEXT,
  "Underlying_Price" REAL,
  "Last_Trade_Date" TIMESTAMP,
  "JSON" TEXT,
  "Quote_Time_txt" TEXT,
  "Last_Trade_Date_txt" TEXT,
  "Expiry_txt" TEXT
);
CREATE INDEX "ix_TLT_Quote_Time"ON "TLT" ("Quote_Time");
CREATE TABLE IF NOT EXISTS "HYG" (
"Quote_Time" TIMESTAMP,
  "Strike" REAL,
  "Type" TEXT,
  "Symbol" TEXT,
  "Last" REAL,
  "Bid" REAL,
  "Ask" REAL,
  "Chg" REAL,
  "PctChg" REAL,
  "Vol" REAL,
  "Open_Int" REAL,
  "IV" REAL,
  "Root" TEXT,
  "IsNonstandard" INTEGER,
  "Underlying" TEXT,
  "Underlying_Price" REAL,
  "Last_Trade_Date" TIMESTAMP,
  "JSON" TEXT,
  "Quote_Time_txt" TEXT,
  "Last_Trade_Date_txt" TEXT,
  "Expiry_txt" TEXT
);
CREATE INDEX "ix_HYG_Quote_Time"ON "HYG" ("Quote_Time");
CREATE TABLE IF NOT EXISTS "SPY" (
"Quote_Time" TIMESTAMP,
  "Strike" REAL,
  "Type" TEXT,
  "Symbol" TEXT,
  "Last" REAL,
  "Bid" REAL,
  "Ask" REAL,
  "Chg" REAL,
  "PctChg" REAL,
  "Vol" REAL,
  "Open_Int" REAL,
  "IV" REAL,
  "Root" TEXT,
  "IsNonstandard" INTEGER,
  "Underlying" TEXT,
  "Underlying_Price" REAL,
  "Last_Trade_Date" TIMESTAMP,
  "JSON" TEXT,
  "Quote_Time_txt" TEXT,
  "Last_Trade_Date_txt" TEXT,
  "Expiry_txt" TEXT
);
CREATE INDEX "ix_SPY_Quote_Time"ON "SPY" ("Quote_Time");
CREATE TABLE IF NOT EXISTS "UNG" (
"Quote_Time" TIMESTAMP,
  "Strike" REAL,
  "Type" TEXT,
  "Symbol" TEXT,
  "Last" REAL,
  "Bid" REAL,
  "Ask" REAL,
  "Chg" REAL,
  "PctChg" REAL,
  "Vol" REAL,
  "Open_Int" REAL,
  "IV" REAL,
  "Root" TEXT,
  "IsNonstandard" INTEGER,
  "Underlying" TEXT,
  "Underlying_Price" REAL,
  "Last_Trade_Date" TIMESTAMP,
  "JSON" TEXT,
  "Quote_Time_txt" TEXT,
  "Last_Trade_Date_txt" TEXT,
  "Expiry_txt" TEXT
);
CREATE INDEX "ix_UNG_Quote_Time"ON "UNG" ("Quote_Time");
CREATE TABLE IF NOT EXISTS "LQD" (
"Quote_Time" TIMESTAMP,
  "Strike" REAL,
  "Type" TEXT,
  "Symbol" TEXT,
  "Last" REAL,
  "Bid" REAL,
  "Ask" REAL,
  "Chg" REAL,
  "PctChg" REAL,
  "Vol" REAL,
  "Open_Int" REAL,
  "IV" REAL,
  "Root" TEXT,
  "IsNonstandard" INTEGER,
  "Underlying" TEXT,
  "Underlying_Price" REAL,
  "Last_Trade_Date" TIMESTAMP,
  "JSON" TEXT,
  "Quote_Time_txt" TEXT,
  "Last_Trade_Date_txt" TEXT,
  "Expiry_txt" TEXT
);
CREATE INDEX "ix_LQD_Quote_Time"ON "LQD" ("Quote_Time");
CREATE TABLE IF NOT EXISTS "IYR" (
"Quote_Time" TIMESTAMP,
  "Strike" REAL,
  "Type" TEXT,
  "Symbol" TEXT,
  "Last" REAL,
  "Bid" REAL,
  "Ask" REAL,
  "Chg" REAL,
  "PctChg" REAL,
  "Vol" REAL,
  "Open_Int" REAL,
  "IV" REAL,
  "Root" TEXT,
  "IsNonstandard" INTEGER,
  "Underlying" TEXT,
  "Underlying_Price" REAL,
  "Last_Trade_Date" TIMESTAMP,
  "JSON" TEXT,
  "Quote_Time_txt" TEXT,
  "Last_Trade_Date_txt" TEXT,
  "Expiry_txt" TEXT
);
CREATE INDEX "ix_IYR_Quote_Time"ON "IYR" ("Quote_Time");
CREATE TABLE IF NOT EXISTS "QQQ" (
"Quote_Time" TIMESTAMP,
  "Strike" REAL,
  "Type" TEXT,
  "Symbol" TEXT,
  "Last" REAL,
  "Bid" REAL,
  "Ask" REAL,
  "Chg" REAL,
  "PctChg" REAL,
  "Vol" REAL,
  "Open_Int" REAL,
  "IV" REAL,
  "Root" TEXT,
  "IsNonstandard" INTEGER,
  "Underlying" TEXT,
  "Underlying_Price" REAL,
  "Last_Trade_Date" TIMESTAMP,
  "JSON" TEXT,
  "Quote_Time_txt" TEXT,
  "Last_Trade_Date_txt" TEXT,
  "Expiry_txt" TEXT
);
CREATE INDEX "ix_QQQ_Quote_Time"ON "QQQ" ("Quote_Time");
CREATE TABLE IF NOT EXISTS "UVXY" (
"Quote_Time" TIMESTAMP,
  "Strike" REAL,
  "Type" TEXT,
  "Symbol" TEXT,
  "Last" REAL,
  "Bid" REAL,
  "Ask" REAL,
  "Chg" REAL,
  "PctChg" REAL,
  "Vol" REAL,
  "Open_Int" REAL,
  "IV" REAL,
  "Root" TEXT,
  "IsNonstandard" INTEGER,
  "Underlying" TEXT,
  "Underlying_Price" REAL,
  "Last_Trade_Date" TIMESTAMP,
  "JSON" TEXT,
  "Quote_Time_txt" TEXT,
  "Last_Trade_Date_txt" TEXT,
  "Expiry_txt" TEXT
);
CREATE INDEX "ix_UVXY_Quote_Time"ON "UVXY" ("Quote_Time");
CREATE TABLE IF NOT EXISTS "VIX" (
"Quote_Time" TIMESTAMP,
  "Strike" REAL,
  "Type" TEXT,
  "Symbol" TEXT,
  "Last" REAL,
  "Bid" REAL,
  "Ask" REAL,
  "Chg" REAL,
  "PctChg" REAL,
  "Vol" REAL,
  "Open_Int" REAL,
  "IV" REAL,
  "Root" TEXT,
  "IsNonstandard" INTEGER,
  "Underlying" TEXT,
  "Underlying_Price" REAL,
  "Last_Trade_Date" TIMESTAMP,
  "JSON" TEXT,
  "Quote_Time_txt" TEXT,
  "Last_Trade_Date_txt" TEXT,
  "Expiry_txt" TEXT
);
CREATE INDEX "ix_VIX_Quote_Time"ON "VIX" ("Quote_Time");
CREATE TABLE IF NOT EXISTS "FXA" (
"Quote_Time" TIMESTAMP,
  "Strike" REAL,
  "Type" TEXT,
  "Symbol" TEXT,
  "Last" REAL,
  "Bid" REAL,
  "Ask" REAL,
  "Chg" REAL,
  "PctChg" REAL,
  "Vol" REAL,
  "Open_Int" REAL,
  "IV" REAL,
  "Root" TEXT,
  "IsNonstandard" INTEGER,
  "Underlying" TEXT,
  "Underlying_Price" REAL,
  "Last_Trade_Date" TIMESTAMP,
  "JSON" TEXT,
  "Quote_Time_txt" TEXT,
  "Last_Trade_Date_txt" TEXT,
  "Expiry_txt" TEXT
);
CREATE INDEX "ix_FXA_Quote_Time"ON "FXA" ("Quote_Time");
CREATE TABLE IF NOT EXISTS "FXF" (
"Quote_Time" TIMESTAMP,
  "Strike" REAL,
  "Type" TEXT,
  "Symbol" TEXT,
  "Last" REAL,
  "Bid" REAL,
  "Ask" REAL,
  "Chg" REAL,
  "PctChg" REAL,
  "Vol" REAL,
  "Open_Int" REAL,
  "IV" REAL,
  "Root" TEXT,
  "IsNonstandard" INTEGER,
  "Underlying" TEXT,
  "Underlying_Price" REAL,
  "Last_Trade_Date" TIMESTAMP,
  "JSON" TEXT,
  "Quote_Time_txt" TEXT,
  "Last_Trade_Date_txt" TEXT,
  "Expiry_txt" TEXT
);
CREATE INDEX "ix_FXF_Quote_Time"ON "FXF" ("Quote_Time");
CREATE TABLE IF NOT EXISTS "BND" (
"Quote_Time" TIMESTAMP,
  "Strike" REAL,
  "Type" TEXT,
  "Symbol" TEXT,
  "Last" REAL,
  "Bid" REAL,
  "Ask" REAL,
  "Chg" REAL,
  "PctChg" REAL,
  "Vol" REAL,
  "Open_Int" REAL,
  "IV" REAL,
  "Root" TEXT,
  "IsNonstandard" INTEGER,
  "Underlying" TEXT,
  "Underlying_Price" REAL,
  "Last_Trade_Date" TIMESTAMP,
  "JSON" TEXT,
  "Quote_Time_txt" TEXT,
  "Last_Trade_Date_txt" TEXT,
  "Expiry_txt" TEXT
);
CREATE INDEX "ix_BND_Quote_Time"ON "BND" ("Quote_Time");
