CREATE TABLE IF NOT EXISTS "DU242089" (
"execid" TEXT,
  "account" TEXT,
  "avgprice" TEXT,
  "clientid" TEXT,
  "comboLegsDescrip" TEXT,
  "combolegs" TEXT,
  "conId" TEXT,
  "current_date" TEXT,
  "current_datetime" TEXT,
  "evmultiplier" TEXT,
  "evrule" TEXT,
  "exchange" TEXT,
  "expiry" TEXT,
  "liquidation" TEXT,
  "localSymbol" TEXT,
  "multiplier" TEXT,
  "orderid" TEXT,
  "permid" TEXT,
  "price" TEXT,
  "primaryExchange" TEXT,
  "qty" TEXT,
  "right" TEXT,
  "secId" TEXT,
  "secIdType" TEXT,
  "shares" TEXT,
  "side" TEXT,
  "strike" TEXT,
  "symbol" TEXT,
  "times" TEXT,
  "underComp" TEXT
);
CREATE INDEX "ix_DU242089_execid"ON "DU242089" ("execid");
